# Chapter 2: Vectors, matrices and multidimensional arrays



- Reference
[Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) by Robert Johansson


In [1]:
import numpy as np

## The NumPy array object

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int32')

In [9]:
data.nbytes

24

## Creating arrays

### Arrays filled with constant values

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
3.0*np.ones(5)

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences

In [13]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
np.linspace(2, 10, 11)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [ ]:
(10-0)/(10-1)

In [ ]:
(10-2)/10

## Index and slicing

### One-dimensional arrays

In [ ]:
a = np.arange(0, 11)

In [ ]:
a

In [ ]:
a[0]  # the first element

In [ ]:
a[-1] # the last element

In [ ]:
a[4]  # the fifth element, at index 4

In [ ]:
a[1:-1]

In [ ]:
a[1:-1:2]

In [ ]:
a[:5]

In [ ]:
a[-5:]

In [ ]:
a[::-2]


## Multidimensional arrays

In [ ]:
L = [[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]]
A = np.array(L)
A

In [ ]:
A.shape

In [ ]:
A[0]

In [ ]:
A[:, 1]  # the second column

In [ ]:
A[1, :]  # the second row

In [ ]:
A[:3, :3]  # upper half diagonal block matrix

In [ ]:
A[3:, :3]  # lower left off-diagonal block matrix

In [ ]:
A[::2, ::2]  # every second element starting from 0, 0

In [ ]:
A[1::2, 1::3]  # every second element starting from 1, 1

### Fancy indexing and Boolean-valued indexing

In [ ]:
A = np.linspace(0,1,11)
A

In [ ]:
A[[0, 2, 4]]

In [ ]:
A[np.array([0, 2, 4])]

In [ ]:
A > 0.5 

In [ ]:
index = A > 0.5
index

In [ ]:
A[index]

In [ ]:
A[A > 0.5]