# Vectors, matrices and multidimensional arrays
### 빅데이터수치해석 입문 및 실습 
### 숙명여자대학교 기계시스템학부 심주용

- Reference
[Numerical Python - A Practical Techniques Approach for Industry](http://www.apress.com/9781484205549) by Robert Johansson



In [1]:
import numpy as np

## The NumPy array object

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int32')

In [9]:
data.nbytes

24

## Creating arrays

### Arrays filled with constant values

In [10]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
3.0*np.ones(5)

array([3., 3., 3., 3., 3.])

### Arrays filled with incremental sequences
![](https://github.com/jooyongsim/numerical2023/blob/main/photos/linspace.PNG?raw=true)
<!-- <img src="https://github.com/jooyongsim/numerical2023/blob/main/photos/linspace.PNG?raw=true"> -->

In [13]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [15]:
np.linspace(2, 10, 11)

array([ 2. ,  2.8,  3.6,  4.4,  5.2,  6. ,  6.8,  7.6,  8.4,  9.2, 10. ])

<img src=

## Index and slicing

### One-dimensional arrays

In [38]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
a[0], a[4], a[-1] #  the first element, the fifth element at index 4, the last element

(0, 4, 10)

In [21]:
a[1:-1], a[1:-1:2]

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [22]:
a[:5], a[-5:]

(array([0, 1, 2, 3, 4]), array([ 6,  7,  8,  9, 10]))

In [23]:
a[::-2]

array([10,  8,  6,  4,  2,  0])

## Multidimensional arrays

In [27]:
L = [[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]]
A = np.array(L)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]])

In [28]:
A.shape

(5, 6)

In [29]:
A[0]

array([0, 1, 2, 3, 4, 5])

In [30]:
A[:, 1]  # the second column

array([ 1, 11, 21, 31, 41])

In [31]:
A[1, :]  # the second row

array([10, 11, 12, 13, 14, 15])

In [32]:
A[:3, :3]  # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [33]:
A[3:, :3]  # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42]])

### Fancy indexing and Boolean-valued indexing

In [37]:
A = np.linspace(0,1,11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [39]:
A[[0, 2, 4]]

array([0. , 0.2, 0.4])

In [40]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [41]:
A > 0.5 

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [42]:
index = A > 0.5
index

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [43]:
A[index]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [44]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

## Reshaping and resizing

In [46]:
data = np.arange(0, 6)
data

array([0, 1, 2, 3, 4, 5])

In [59]:
data = data.reshape(2,3)
data

array([[0, 3, 1],
       [4, 2, 5]])

In [60]:
data.shape

(2, 3)

In [54]:
data = data.transpose()
data

array([[0, 3],
       [1, 4],
       [2, 5]])

In [55]:
data = data.reshape(2,3)
data

array([[0, 3, 1],
       [4, 2, 5]])

In [56]:
data.flatten()

array([0, 3, 1, 4, 2, 5])

In [57]:
data.flatten().shape

(6,)

In [62]:
data.shape

(2, 3)

In [63]:
data[:, np.newaxis].shape

(2, 1, 3)

In [81]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [82]:
np.stack((data, data, data), axis = 0)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [83]:
np.stack((data, data, data), axis = 1)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [84]:
np.stack((data, data, data), axis = 1).shape

(5, 3)

In [88]:
data = np.arange(5)
data = data[:, np.newaxis]
np.stack((data, data, data), axis = 0).shape

(3, 5, 1)

In [89]:
np.stack((data, data, data), axis = 1).shape

(5, 3, 1)

In [90]:
data.shape

(5, 1)

In [91]:
np.stack((data, data, data), axis = 2).shape

(5, 1, 3)

## Broad Casting

In [95]:
z = np.arange(1,6)
z

array([1, 2, 3, 4, 5])

In [96]:
x = np.arange(0,15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [101]:
x.shape, z.shape

((3, 5), (5,))

In [102]:
x / z

array([[ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ],
       [ 5.        ,  3.        ,  2.33333333,  2.        ,  1.8       ],
       [10.        ,  5.5       ,  4.        ,  3.25      ,  2.8       ]])

In [103]:
z[:,np.newaxis].shape

(5, 1)

In [104]:
x / z[:,np.newaxis]

ValueError: operands could not be broadcast together with shapes (3,5) (5,1) 

In [105]:
z[np.newaxis,:].shape

(1, 5)

In [106]:
x / z[np.newaxis,:]

array([[ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ],
       [ 5.        ,  3.        ,  2.33333333,  2.        ,  1.8       ],
       [10.        ,  5.5       ,  4.        ,  3.25      ,  2.8       ]])

## Concatenation

In [117]:
z

array([[2, 4]])

In [118]:
z.shape

(1, 2)

In [121]:
zz = np.concatenate([z, z, z], axis=0)
zz

array([[2, 4],
       [2, 4],
       [2, 4]])

In [119]:
zz.shape

(3, 2)

In [120]:
zz = np.concatenate([z[0], z[0], z[0]], axis=0)
zz

array([2, 4, 2, 4, 2, 4])

In [123]:
z = np.array([[2], [4]])

In [124]:
z.shape

(2, 1)

In [126]:
zz = np.concatenate([z, z], axis=1)
zz

array([[2, 2],
       [4, 4]])

In [127]:
zz = np.concatenate([z, z], axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

## Matrix Operations

In [130]:
np.linalg.det([[1,2],[3,4]])

-2.0000000000000004

In [131]:
np.linalg.matrix_rank([[1,2],[3,4]])

2

In [132]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])
X, Y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [133]:
X*Y

array([[ 5, 12],
       [21, 32]])

In [134]:
X@Y

array([[19, 22],
       [43, 50]])

In [135]:
np.dot(X,Y)

array([[19, 22],
       [43, 50]])

In [ ]:
X = np.array(range(0,25)).reshape(5,5)
X
