In [1]:
!echo %cd%

C:\Users\admin\Dropbox (Personal)\Courses\수치해석 2021\Python


In [1]:
import numpy as np

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
M = np.array([1,2,3,4]).reshape(2,2)
M

array([[1, 2],
       [3, 4]])

In [6]:
M_inv = np.linalg.inv(M)
M_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [9]:
iden = np.matmul(M,M_inv)
iden


array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [10]:
np.round(iden,5)

array([[1., 0.],
       [0., 1.]])

In [13]:
np.round(M@M_inv,5)

array([[1., 0.],
       [0., 1.]])

In [14]:
np.round(M_inv@M,5)

array([[1., 0.],
       [0., 1.]])

In [15]:
np.linalg.eig(M)

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [16]:
A = [7.3, 0.2, -3.7, -11.5, 1, 5.5, 17.7, 1.8, -9.3]
A = np.array(A).reshape((3,3))
A

array([[  7.3,   0.2,  -3.7],
       [-11.5,   1. ,   5.5],
       [ 17.7,   1.8,  -9.3]])

In [19]:
eig, X = np.linalg.eig(A)
np.round(eig,5), np.round(X,5)

(array([-4., -0.,  3.]),
 array([[-0.30151,  0.43644, -0.30151],
        [ 0.30151,  0.21822,  0.90453],
        [-0.90453,  0.87287, -0.30151]]))

In [26]:
#D = X_inv*A*X
X_inv = np.linalg.inv(X)
X_inv

array([[ 4.31161223,  0.66332496, -2.32163735],
       [ 3.66606056,  0.91651514, -0.91651514],
       [-2.32163735,  0.66332496,  0.99498744]])

In [28]:
np.round(X_inv@A@X,5)

array([[-4.,  0., -0.],
       [-0.,  0., -0.],
       [ 0.,  0.,  3.]])